version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: miapp
    ports:
      - "3306:3306"

  node_api:
    build: .
    ports:  
      - "3000:3000"
    depends_on:
      - mysql_db